import pandas as pd, matplotlib.pyplot as plt
df = pd.read_csv('data/processed/fig01_woelders_eth_usdc.csv')
x = range(len(df))
plt.figure(figsize=(8,5))
plt.bar([i-0.35/2 for i in x], df['v2'], 0.35, label='v2')
plt.bar([i+0.35/2 for i in x], df['v3'], 0.35, label='v3')
plt.xticks(list(x), df['metric'], rotation=15)
plt.ylabel('Value (unitless)')
plt.title('Woelders (2022): ETH–USDC Decomposition (2021-05-06→2022-06-01)')
plt.legend(); plt.tight_layout()
plt.savefig('figures/fig01_woelders_eth_usdc.png', dpi=200)
